name: verty
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.3.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.1.0
  geolocator: ^8.2.0
  provider: ^6.0.0
  supabase_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
       - assets/engine_parts.png
       - assets/body_parts.png
       - assets/transmission.png
       - assets/fuel_system.png
       - assets/brake_system.png
       - assets/suspension.png
       - assets/steering.png
       - assets/electrical_parts.png
   
   
